In [43]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.metrics import accuracy_score

In [44]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [45]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [46]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [47]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [55]:
knn = KNNImputer(n_neighbors=3,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf= knn.fit_transform(X_test)

In [56]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

     Pclass   Age      Fare
0       1.0  45.5   28.5000
1       2.0  23.0   13.0000
2       3.0  32.0    7.9250
3       3.0  26.0    7.8542
4       3.0   6.0   31.2750
..      ...   ...       ...
707     3.0  21.0    7.6500
708     1.0  37.0   31.0000
709     3.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [57]:
lr=LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred=lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7597765363128491

# comparsison with simple imputer

In [58]:
si = SimpleImputer()

X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.fit_transform(X_test)

In [59]:
lr=LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2=lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.7374301675977654