In [1]:
import pandas as pd

# working with json

In [2]:
df=pd.read_json('train.json')

In [3]:
df.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

# working with SQL

In [10]:
!pip install --upgrade mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp314-cp314-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 2.1 MB/s  0:00:09a 0:00:01[36m0:00:01:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [1]:
import mysql.connector
conn=mysql.connector.connect(host='localhost',user='root',password='Kunal@1122',database='IMS')
cursor=conn.cursor()

In [2]:
import os

os.listdir()

['.DS_Store',
 'test.csv',
 'Working-with-csv.ipynb',
 'zomato.csv',
 'sqlpractice.sql',
 'IPL Matches 2008-2020.csv',
 'aug_train.csv',
 'movie_titles_metadata.tsv',
 'train.json',
 '.ipynb_checkpoints',
 'Work-with-Json and SQL.ipynb']

In [3]:
with open("sqlpractice.sql", "r") as file:
    print(file.read(1000))

use world;
select Name
from city
where Population > 1000000;

select Name
from country
where IndepYear > 1945;

`PRIMARY`select Code, count(*)
from city C, country CC
where CountryCode = code
group by code;

select Code, count(*)
from city C, country CC
where CountryCode = code
    and C.Population > 1000000
group by code;

select CC.Name
from city C, country CC
where CountryCode = code
group by CC.Name
having max(C.Population) < 1000000;

#this should be equivalent to previous but it's not because:
#there are 7 countries (Antartica, some colonies) that have no cities.
#which answer is correct?
select distinct Name
from country
where code NOT IN (Select CountryCode
                   from city
				    where Population >= 1000000);

select Name
from country where SurfaceArea = (select max(SurfaceArea) from country);

select GovernmentForm, count(*)
from country
group by GovernmentForm;

select GovernmentForm
from country
order by GNP desc
limit 5;

In [6]:
import pandas as pd
pd.read_sql_query("SELECT * FROM Customers",conn)

/var/folders/h3/bq35s69x0w37k37lsfys42dw0000gn/T/ipykernel_69097/2033940914.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM Customers",conn)

,customer_id,customer_name,email,phone,address,city,state,country,postal_code,customer_type,status,created_at,updated_at,user_id,reminder_interval_days
0,2,manu sharma,manu@gmail.com,9548549805,None,None,None,None,None,Business,Active,2026-08-07 18:45:03,2026-08-07 18:45:03,NaN,7
1,3,Shop Test,shoptest@example.com,9999999999,None,None,None,None,None,Individual,Active,2026-08-08 15:25:05,2026-08-08 15:25:05,10.0,7
2,5,Shop Test,kunalsharma000780+shoptest@gmail.com,8888888888,None,None,None,None,None,Individual,Active,2026-08-08 15:26:09,2026-08-08 15:26:09,12.0,7
3,6,manav,ziglycartoon95@gmail.com,NaN,None,None,None,None,None,Individual,Active,2026-08-08 15:52:22,2026-08-08 15:52:22,13.0,7